export default {
  jobs: {"geocodeTitle":"Photon reverse geocoding","geocodeDescription":"Queue address lookups for completed trips with GPS points (up to 500 per run).","geocodeMode":"Trip selection","geocodeMissing":"Only trips with missing addresses","geocodeAll":"All trips (existing addresses are preserved)","startGeocode":"Start reverse geocoding","starting":"Starting…","queuedMessage":"{count} jobs queued for processing.","title":"Background jobs","description":"Monitor Redis queues and manage failed jobs.","refresh":"Refresh","redis":"Redis","online":"Connected","offline":"Disconnected","pending":"Pending","processing":"Processing","delayed":"Delayed","failed":"Failed","type":"Type","id":"Job ID","attempts":"Attempts","error":"Error","actions":"Actions","retry":"Retry","delete":"Remove","confirmDelete":"Permanently remove this failed job?","empty":"No jobs in this queue."},

  tripGpsView:{label:"GPS display",route:"Route",both:"Route & points",points:"Points only",pointsCount:"GPS points"},
  tripDetails:{title:"Trip details",details:"Details",history:"History",start:"Start",end:"End",from:"Origin",to:"Destination",distance:"Distance",vehicle:"Vehicle",category:"Category",tags:"Tags",noTags:"No tags available",save:"Save changes",categoryRequired:"Please select a category."},
  tripArchive:{open:"Archive",close:"Close",title:"Deleted trips",retention:"Trips are permanently deleted after 90 days.",empty:"No archived trips.",purgeAt:"Permanent deletion",restore:"Restore",deleteForever:"Delete permanently",moveToArchive:"Delete trip",confirmArchive:"Move this trip to the archive for 90 days?",confirmDelete:"Permanently delete this trip? This cannot be undone."},
  common:{save:"Save",saving:"Saving …",cancel:"Cancel",close:"Close",loading:"Loading …",language:"Language",german:"German",english:"English",systemDefault:"System default"},
  nav:{dashboard:"Dashboard",vehicles:"Vehicles",statistics:"Statistics",export:"Export",compliance:"Compliance",profile:"Profile",settings:"Administration",logout:"Sign out"},
  language:{globalTitle:"Default language",globalHint:"This language is used when a user has not selected a personal language.",personalTitle:"Language",personalHint:"Overrides the global default language for your user account only."},
  vehicles:{activeTab:"Vehicles",archiveTab:"Archive",archiveEmpty:"The archive is empty",archiveEmptyHint:"Archived vehicles appear here and can be restored.",archiveConfirm:"Archive vehicle “{vehicle}”? Existing trips and history are retained.",archivedMessage:"Vehicle “{vehicle}” was archived.",restoredMessage:"Vehicle “{vehicle}” was restored from the archive and is initially deregistered.",restore:"Restore",archivedAt:"Archived on",plate:"License plate",registerAgain:"Reactivate",registeredMessage:"Vehicle “{vehicle}” has been reactivated.",title:"My vehicles",share:"Share",shareTitle:"Share vehicle",email:"Email address",emailMode:"By email address",linkMode:"By sharing link",createLink:"Create sharing link",copy:"Copy",unknownLink:"Link is unknown.",expiredLink:"Link has expired",accept:"Accept",decline:"Decline"},
  statistics:{title:"Statistics"},
  dashboard:{title:"Logbook"},
  profile:{title:"Profile settings"},
  admin:{title:"System settings",saved:"System settings have been saved."},
  login:{title:"Sign in to Fahrtenbuch",email:"Email address",password:"Password",totp:"Two-factor code",remember:"Keep me signed in",forgot:"Forgot password?",submitting:"Signing in …",submit:"Sign in",or:"Or sign in with",passkey:"Sign in with passkey",mfaRequired:"Enter your two-factor code.",failed:"Sign-in failed.",passkeyFailed:"Passkey sign-in failed."},
  shareInvitation:{section:"Vehicle sharing",title:"Invitation",checking:"Checking invitation …",notFound:"The invitation was not found.",unknown:"Link is unknown.",expired:"Link has expired",expiredHint:"This sharing link is no longer valid. Ask the vehicle owner for a new link.",accepted:"Vehicle sharing accepted",acceptedHint:"“{vehicle}” is now shared with you.",toVehicles:"Go to vehicles",declined:"Invitation declined",declinedHint:"No vehicle sharing permission was created.",wrongUser:"Invitation for another user",wrongUserHint:"Sign in with the account whose email address received this invitation.",request:"{owner} wants to share a vehicle with you",vehicle:"Vehicle",validUntil:"Valid until {date}",privacy:"By accepting, you can use the vehicle for your own trips. Vehicle master data, Bluetooth configuration, leasing/financing data and vehicle-wide statistics remain restricted to the owner."},
  odometer:{readingLog:"Odometer reading log",reading:"reading",readings:"readings",vehicle:"Vehicle",close:"Close",empty:"No readings yet.",source:"Source",manual:"Manual",selectEdit:"Select to edit",title:"Odometer reading for {month}",missing:"The monthly odometer reading for {vehicle} is missing. It is used to identify unrecorded distance in statistics.",last:"Last reading: {value} km",value:"Odometer",later:"Remind me later",saving:"Saving …",invalid:"Enter a valid odometer reading."},
  vehicleEditor:{nameRequired:"Enter a vehicle name.",contractDateOrder:"The contract end date must be after the contract start date.",contractIncomplete:"For mileage forecasting, enter the contract start, contract end and mileage limit.",saveFailed:"The vehicle could not be saved.",edit:"Edit vehicle",create:"Add vehicle",ownerHint:"This vehicle belongs exclusively to your user account.",name:"Vehicle name",plate:"License plate",manufacturer:"Manufacturer",model:"Model",odometer:"Odometer",color:"Color",bluetooth:"Bluetooth MAC",acquisition:"Acquisition type",contractHint:"Contract data is optional. If term and mileage limit are provided, statistics can forecast mileage.",contractStart:"Contract start",contractEnd:"Contract end",kmLimit:"Mileage limit",notes:"Notes",default:"Use as default vehicle",defaultHint:"New trips use this vehicle as the default selection.",save:"Save vehicle"},
  vehicleLifecycle:{register:"Reactivate vehicle",registerHint:"Reactivation starts a new active vehicle period from the selected date. Previous deregistrations and trips remain unchanged in the history.",registrationDate:"Registration date",confirmRegister:"Reactivate",deregister:"Deregister vehicle",transfer:"Transfer ownership",deregisterHint:"After deregistration, the vehicle is blocked for new trips and tracking. No further odometer readings or other new vehicle data can be recorded. Existing data and trips remain available.",confirm:"I confirm that no further mileage can be driven or recorded in the logbook for this vehicle after deregistration.",transferHint:"The current ownership period remains in place until the transfer date. From that date, the vehicle belongs to the new user. The new owner's earlier own trips remain visible to them; trips from other users are not shared.",newOwner:"New owner",accountPlaceholder:"Username or email",date:"Transfer date",confirmDeregister:"Deregister permanently"}
,
  shell:{openMenu:"Open main menu",openUserMenu:"Open user menu",user:"User"}
};
