export default {
  common:{save:"Save",cancel:"Cancel",loading:"Loading …",language:"Language",german:"German",english:"English",systemDefault:"System default"},
  nav:{dashboard:"Dashboard",vehicles:"Vehicles",statistics:"Statistics",export:"Export",compliance:"Compliance",profile:"Profile",settings:"Administration",logout:"Sign out"},
  language:{globalTitle:"Default language",globalHint:"This language is used when a user has not selected a personal language.",personalTitle:"Language",personalHint:"Overrides the global default language for your user account only."},
  vehicles:{title:"My vehicles",share:"Share",shareTitle:"Share vehicle",email:"Email address",emailMode:"By email address",linkMode:"By sharing link",createLink:"Create sharing link",copy:"Copy",unknownLink:"Link is unknown.",expiredLink:"Link has expired",accept:"Accept",decline:"Decline"},
  statistics:{title:"Statistics"},
  dashboard:{title:"Logbook"},
  profile:{title:"Profile settings"},
  admin:{title:"System settings",saved:"System settings have been saved."},
  login:{title:"Sign in to Fahrtenbuch",email:"Email address",password:"Password",totp:"Two-factor code",remember:"Keep me signed in",forgot:"Forgot password?",submitting:"Signing in …",submit:"Sign in",or:"Or sign in with",passkey:"Sign in with passkey",mfaRequired:"Enter your two-factor code.",failed:"Sign-in failed.",passkeyFailed:"Passkey sign-in failed."},
  shareInvitation:{section:"Vehicle sharing",title:"Invitation",checking:"Checking invitation …",notFound:"The invitation was not found.",unknown:"Link is unknown.",expired:"Link has expired",expiredHint:"This sharing link is no longer valid. Ask the vehicle owner for a new link.",accepted:"Vehicle sharing accepted",acceptedHint:"“{vehicle}” is now shared with you.",toVehicles:"Go to vehicles",declined:"Invitation declined",declinedHint:"No vehicle sharing permission was created.",wrongUser:"Invitation for another user",wrongUserHint:"Sign in with the account whose email address received this invitation.",request:"{owner} wants to share a vehicle with you",vehicle:"Vehicle",validUntil:"Valid until {date}",privacy:"By accepting, you can use the vehicle for your own trips. Vehicle master data, Bluetooth configuration, leasing/financing data and vehicle-wide statistics remain restricted to the owner."},
  odometer:{readingLog:"Odometer reading log",reading:"reading",readings:"readings",vehicle:"Vehicle",close:"Close",empty:"No readings yet.",source:"Source",manual:"Manual",selectEdit:"Select to edit",title:"Odometer reading for {month}",missing:"The monthly odometer reading for {vehicle} is missing. It is used to identify unrecorded distance in statistics.",last:"Last reading: {value} km",value:"Odometer",later:"Remind me later",saving:"Saving …",invalid:"Enter a valid odometer reading."}
};
